### ISSUE TITLE
Getting a warning message using the custom widget

### ISSUE THREAD

**Issue by premtemp1** [happeo/custom-widget-templates#22]
Hello,
  I am getting this warning in the browser . Can you tell me how to fix this.

[Custom widget] Widget settings declared without edit mode. Data will not be stored to remote.

Thanks

**Comment by mikamaunula** [comment]
Hey! 

Thanks for the report.

Actually, it is not a warning. It is just info print that settings are not saved in view -mode. 
I'll create a follow-up issue for our platform for removing info print in this case because it is confusing.

-mika
