### ISSUE TITLE
Reading a shared file

### ISSUE THREAD

**Issue by premtemp1** [happeo/custom-widget-templates#23]
Hello,
  Not a bug, but I was checking to see if there is an option to have a google file picker that upload a file from google drive . 

I have custom widget and want the upload a file containing some data  from google drive, read the content and use it in my custom widget .

In the constant.js file you can define text widget settings. is there an option to have a file picker as setting parameter?

if not, do you any option available to read a google shared file and display in a widget?

Also, is there a limit to  value field in a text widget

{
    placeholder: "Another setting",
    key: "anotherUniqueKey",
    **value: "this is text",**
    type: "text",
  },

Thanks for your help

**Comment by mikamaunula** [comment]
Hey!

Thanks for the question! You can find supported settings from this link https://github.com/happeo/widgets-sdk/wiki/Declaring-settings-to-the-Happeo-UI.

If you cannot find the correct setting type from the list. You can implement your own custom settings inside the widget using the mode boolean (edit mode == show settings, view mode == hide settings).

-mika
