### ISSUE TITLE
npm registry not found

### ISSUE THREAD

**Issue by SardineDude1** [happeo/custom-widget-templates#32]
My issue:
I am having an issue when attempting to run 'npm install && npm start' to run react locally.
I get the following 404 error:

`npm ERR! 404 Not Found - GET https://registry.npmjs.org/@happeouikit/menus/-/menus-1.2.41-loic.3.tgz - Not found`

My workaround:
Checking the package-lock.js file in the react directory this request appears on line 2743.

Changing the resolved value to 'https://registry.npmjs.org/@happeouikit/menus/-/menus-1.2.41.tgz' and the integrity value to the corresponding value in the npm registry, the issue was resolved.

**Comment by mosa-riel** [comment]
Can confirm this works.

**Comment by cuzo151** [comment]
This is still an issue and the commented fix did not work on my local dev run : https://github.com/happeo/custom-widget-templates/issues/32

[Attached logs ](https://mail.google.com/mail/u/0?ui=2&ik=253c4cf7bf&attid=0.2&permmsgid=msg-a:r-8019368689312078859&view=att&disp=safe&realattid=f_m1851tjt0)for initial run (according [to docs](https://github.com/happeo/custom-widget-templates/tree/main?tab=readme-ov-file#react))
& tried commented registry edit with no success.

**Comment by bhorkarg** [comment]
Now working on the latest main branch
